<?php

namespace App\Filament\Widgets;

use App\Models\Event;
use App\Models\User;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Card;

class StatsOverview extends BaseWidget
{
    protected static ?int $sort = 2;

    protected function getCards(): array
    {
        return [
            //
            Card::make(__('filament::common.clients'), User::where('role_id' , 3)->count()),
            Card::make(__('filament::common.employees'), User::where('role_id' , 2)->count()),
            Card::make(__('filament::common.projects'), Event::where('start' , '>=', now()->subDays(30))->count()),


        ];
    }

    public static function canView(): bool
    {
//        return parent::canView(); // TODO: Change the autogenerated stub
        return auth()->user()->isAdmin();
    }
}
